# conda environment for pose estimation tools
name: workout

channels:
  - anaconda
  - conda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip3
  - ipython
  - pylint>=2.5.0
  - pycodestyle
  - pip:
      - scipy
      - pyyaml
      - pytest
      - flask
      - opencv-python
      - numpy
  - pip3:
      - torch
      - torchvision
      - torchaudio
