# conda environment for pose estimation tools
name: workout

channels:
  - anaconda
  - conda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - ipython
  - pylint>=2.5.0
  - pycodestyle
  - libgcc>=4.8.5
  - opencv
  - pip:
      - scipy
      - pyyaml
      - pytest
      - flask
      - opencv-python
      - numpy
