# conda environment for pose estimation tools
name: workout

channels:
  - anaconda
  - conda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - ipython
  - pylint>=2.5.0
  - pycodestyle
  - pytorch>=1.8
  - pip:
      - scipy
      - pyyaml
      - pytest
      - flask
      - opencv-python
